version: '3'
volumes: {home:, db:, msdb:, minio1:, minio2:, redis:, npm:}
services:
  db:
    environment: ["POSTGRES_USER=django", "POSTGRES_PASSWORD=django"]
    image: "mdillon/postgis:9.6-alpine"
    volumes: ["db:/var/lib/postgresql/data"]
  msdb:
    environment: ["ACCEPT_EULA=Y", "SA_PASSWORD=djangoA1"]
    image: "microsoft/mssql-server-linux"
    volumes: ["msdb:/var/opt/mssql"]
  redis:
    image: "redis:3.2-alpine"
    volumes: ["redis:/data"]
  minio:
    command: "server /export"
    environment: ["MINIO_ACCESS_KEY=djangos3", "MINIO_SECRET_KEY=djangos3"]
    image: "minio/minio"
    volumes: ["minio1:/export", "minio2:/root/.config"]
  backend: &backend
    image: "ionata/backend"
    command: "pipenv run django-admin runserver_plus 0.0.0.0:8000 --nopin"
    links: ["db", "minio", "msdb", "redis"]
    environment:
      DJANGO_SETTINGS_MODULE: "dj_core.settings"
      DJCORE_APP_NAME: "${COMPOSE_PROJECT_NAME:-blankproject}"
      DJCORE_DEBUG: "1"
      DJCORE_DEFAULT_FROM_EMAIL: "Ionata Developers <no-reply@dev.ionata.com>"
      DJCORE_SECRET_KEY: "super_secret_secret_key"
      DJCORE_SERVER_EMAIL: "no-reply@ionata.com"
      PYTHONPATH: "/var/www"
      PYTHONDONTWRITEBYTECODE: "nope"
    stdin_open: true
    tty: true
    volumes:
      - "home:/root"
      - "${BACKEND_ROOT:-./backend}:/var/www"
  celery:
    <<: *backend
    command: "pipenv run celery worker -A dj_core -l info -B"
  frontend:
    command: "npm run --prefix /var/www dev"
    image: "node"
    volumes: ["${FRONTEND_ROOT:-./frontend}:/var/www"]
  web:
    image: "nginx:mainline-alpine"
    links: ["backend", "minio"]
    ports: ["${OUTPORT:-8000}:80"]
    volumes:
      - "./deployment/conf/docker/nginx-${NGINX_CONF:-spa}.conf:/etc/nginx/nginx.conf"
      - "${FRONTEND_ROOT:-./frontend}:/var/www"
