version: '3'
volumes: {home:, db:, msdb:, var:, denv:, venv:, minio1:, minio2:, redis:, npm:}
services:
  db:
    environment: ["POSTGRES_USER=django", "POSTGRES_PASSWORD=django"]
    image: "mdillon/postgis:9.6-alpine"
    volumes: ["db:/var/lib/postgresql/data"]
  msdb:
    environment: ["ACCEPT_EULA=Y", "SA_PASSWORD=djangoA1"]
    image: "microsoft/mssql-server-linux"
    volumes: ["msdb:/var/opt/mssql"]
  redis:
    image: "redis:3.2-alpine"
    volumes: ["redis:/data"]
  minio:
    command: "server /export"
    environment: ["MINIO_ACCESS_KEY=djangos3", "MINIO_SECRET_KEY=djangos3"]
    image: "minio/minio"
    volumes: ["minio1:/export", "minio2:/root/.config"]
  backend: &backend
    command: "/bin/true"
    build: "./deployment/conf/docker/"
    image: "ionata_backend"
    links: ["db", "redis"]
    environment:
      - "DJANGO_SETTINGS_MODULE=dj_core.settings"
      - "DJCORE_APP_NAME=${COMPOSE_PROJECT_NAME:-blankproject}"
      - "DJCORE_DEBUG=1"
      - "DJCORE_SECRET_KEY=super_secret_secret_key"
      - "PYTHONDONTWRITEBYTECODE=nope"
    stdin_open: true
    tty: true
    volumes:
      - "var:/var/www/var"
      - "venv:/var/www/venv"
      - "denv:/var/www/denv"
      - "home:/root"
      - "./deployment:/var/www/deployment"
      - "${BACKEND_ROOT:-./backend}:/var/www/backend"
  celery:
    <<: *backend
    command: "/var/www/deployment/deploy.py celery worker -A dj_core -l info -B"
  runserver:
    <<: *backend
    command: "/var/www/deployment/deploy.py run-dev"
  frontend:
    command: "npm run --prefix /var/www dev"
    image: "ionata_backend"
    volumes: ["${FRONTEND_ROOT:-./frontend}:/var/www"]
    depends_on: ["backend"]
  web:
    image: "nginx:mainline-alpine"
    volumes: ["./deployment/conf/docker/nginx-${NGINX_CONF:-spa}.conf:/etc/nginx/nginx.conf"]
    links: ["runserver", "minio"]
    ports: ["${OUTPORT:-8000}:80"]
