version: '3'
services:
  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - "./var/db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

  redis:
    image: redis:3.2-alpine
    volumes:
      - "./var/redis:/data"

  backend:
    depends_on:
      - db
      - redis
    image: dangerfarms/geodrf-alpine:latest
    links:
      - db
      - redis
    volumes:
      - "./deployment:/var/www/deployment"
      - "./denv:/var/www/venv"
      - "./backend:/var/www/backend"
      - "./var:/var/www/var"
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: "/var/www/deployment/deploy run-dev"
    expose:
      - "8000"
    stdin_open: true
    tty: true

  celery:
    depends_on:
      - db
      - redis
    image: dangerfarms/geodrf-alpine:latest
    links:
      - db
      - redis
    volumes:
      - "./deployment:/var/www/deployment"
      - "./denv:/var/www/venv"
      - "./backend:/var/www/backend"
      - "./var:/var/www/var"
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: "/var/www/deployment/deploy run celery worker -A wagtailnest -l info -B"

  frontend:
    image: node:boron-alpine
    volumes:
      - "./frontend:/usr/src/app"
    working_dir: "/usr/src/app"
    command: "npm run dev"
    expose:
      - "8000"
    stdin_open: true
    tty: true

  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx:1.11-alpine
    links:
      - backend
      - frontend
    volumes:
      - "./var:/var/www/var"
      - "./deployment/conf/docker/nginx:/etc/nginx/conf.d"
    ports:
      - "8000:8000"
