version: '3'
services:

  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - "./var/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "django"
      POSTGRES_USER: "django"
      POSTGRES_DB: "django"
      PGPASSWORD: "django"

  redis:
    image: redis:3.2-alpine
    volumes:
      - "./var/redis:/data"

  backend:
    depends_on:
      - db
    image: dangerfarms/geodrf-alpine:latest
    links:
      - db
    volumes:
      - "./deployment:/var/www/deployment"
      - "./denv:/var/www/venv"
      - "./backend:/var/www/backend"
      - "./var:/var/www/var"
    environment:
      DJANGO_SETTINGS_MODULE: "${COMPOSE_PROJECT_NAME}.settings.local"
      PYTHONDONTWRITEBYTECODE: "1"
      WAGTAILNEST_DEBUG: "True"
    command: "/var/www/deployment/deploy run-dev 0.0.0.0:8000"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  celery:
    depends_on:
      - db
      - redis
    image: dangerfarms/geodrf-alpine:latest
    links:
      - db
      - redis
    volumes:
      - "./deployment:/var/www/deployment"
      - "./denv:/var/www/venv"
      - "./backend:/var/www/backend"
      - "./var:/var/www/var"
    environment:
      DJANGO_SETTINGS_MODULE: "${COMPOSE_PROJECT_NAME}.settings.local"
      PYTHONDONTWRITEBYTECODE: "1"
      WAGTAILNEST_DEBUG: "True"
    command: "/var/www/deployment/deploy run celery worker -A wagtailnest -l info -B -f /var/www/var/logs/celery.log"
