#!/usr/bin/env bash
VAR_DIRS="var/cache var/logs var/www/static var/www/media/uploads"
DEPLOYED="var/.deployed"
SECRETS_PY="backend/src/local_secrets.py"
ACTIONS=("run" "run-dev" "update" "install")
set -x

_has_command(){ command -v "$1" 2>&1 >/dev/null; }

_permissions(){
  sudo chown -R www-data:ubuntu var "$SECRETS_PY"
  sudo chmod -R u=rwX,g=rwsX,o= var
  sudo chmod -R u=r,g=r,o= "$SECRETS_PY"
}

_venv(){
  python3 -mvenv venv
  [[ -f backend/local.requirements.txt ]] && venv/bin/pip install --upgrade -r backend/local.requirements.txt
  [[ -f backend/requirements.txt ]] && venv/bin/pip install --upgrade -r backend/requirements.txt
  echo "$(pwd)/backend/src/" > venv/lib/python3.5/site-packages/backend.pth
}

_restart(){
  sudo systemctl restart production_gunicorn
  sudo systemctl restart production_celery
}

install(){
  [[ -z "$1" ]] && echo "No repository specified" && exit 1
  git clone --recursive "$1" backend
  update
}

update(){
  mkdir -p $VAR_DIRS
  [[ -f "$SECRETS_PY" ]] || echo "SECRET_KEY = '$(head -c36 /dev/urandom | base64 )'" > "$SECRETS_PY"
  _has_command sudo && _permissions
  git pull && git submodule update
  git -C backend pull && git -C backend submodule update
  if [[ -d "frontend" ]]; then
    git -C frontend pull && git -C frontend submodule update
    _has_command npm && npm --prefix frontend run build
  fi
  _venv
  . ./venv/bin/activate
  django-admin collectstatic --noinput
  django-admin migrate --noinput
  _has_command systemctl && _restart
  touch "$DEPLOYED"
}

run(){
  [[ -f "$DEPLOYED" ]] || update
  . ./venv/bin/activate
  eval "$@"
}

run-dev(){ run "django-admin runserver_plus --pm --nopin $@"; }

cd $(dirname $(dirname $(readlink -f "$0")))  # Change to ..
for action in "${ACTIONS[@]}"; do
	[[ "$action" == "$1" ]] && { eval "$@"; exit 0; }
done
echo "Invalid action specified: $action" && exit 1
